# Generated by Django 4.1.3 on 2022-12-19 21:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("goods", "0001_initial"),
        ("chat", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="auctionparticipant",
            name="goods",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="goods.goods"
            ),
        ),
        migrations.AddField(
            model_name="auctionparticipant",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
