# Generated by Django 4.1.3 on 2022-12-22 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradechatroom',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
