# Generated by Django 4.1.3 on 2022-12-26 02:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_bid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0003_tradechatroom_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.goods')),
            ],
            options={
                'db_table': 'AuctionMessage',
            },
        ),
    ]
