# Generated by Django 4.1.3 on 2022-12-19 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freearticle',
            name='content',
            field=models.TextField(null=True, verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='freearticle',
            name='title',
            field=models.CharField(max_length=50, null=True, verbose_name='제목'),
        ),
        migrations.AlterField(
            model_name='reportarticle',
            name='content',
            field=models.TextField(null=True, verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='reportarticle',
            name='title',
            field=models.CharField(max_length=50, null=True, verbose_name='제목'),
        ),
    ]
