# Generated by Django 4.1.3 on 2022-12-12 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='freearticle',
            name='hits',
            field=models.IntegerField(default=0),
        ),
    ]
