# Generated by Django 4.1.3 on 2022-12-20 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_alter_freearticle_content_alter_freearticle_title_and_more'),
        ('board', '0003_alter_freearticle_options'),
    ]

    operations = [
    ]
