# Generated by Django 4.1.3 on 2022-12-20 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_merge_20221220_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freearticle',
            name='title',
            field=models.CharField(max_length=20, null=True, verbose_name='제목'),
        ),
        migrations.AlterField(
            model_name='reportarticle',
            name='title',
            field=models.CharField(max_length=20, null=True, verbose_name='제목'),
        ),
    ]
