# Generated by Django 4.1.3 on 2022-12-20 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_alter_freearticle_title_alter_reportarticle_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freearticle',
            name='content',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='reportarticle',
            name='content',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='내용'),
        ),
    ]
