# Generated by Django 4.1.3 on 2022-12-20 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_alter_freearticle_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freearticle',
            name='title',
            field=models.CharField(default=1, max_length=20, verbose_name='제목'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reportarticle',
            name='title',
            field=models.CharField(default=1, max_length=20, verbose_name='제목'),
            preserve_default=False,
        ),
    ]
